class Config:
    AGGREGATION_SERVER_URL = "http://localhost:8080"
    
    DATASET_NAME = "Cora"
    NUM_CLIENTS = 3
    HIDDEN_DIM = 64
    NUM_EPOCHS_PER_ROUND = 5
    LEARNING_RATE = 0.01
    DROPOUT = 0.5
    
    CLIENT_API_BASE_PORT = 5000
    
    MIN_SAMPLES_PER_CLIENT = 5
    NON_IID_PARTITION = True
    ALLOW_PARTIAL_CLASSES = True
    
    EXTRACT_REAL_SUBGRAPH = True
    ADD_SELF_LOOPS_FOR_ISOLATED = True
    
    GRADIENT_CLIP_MAX_NORM = 1.0
    USE_SAFE_LOSS_CALCULATION = True
